apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dashboard.yaml

configMapGenerator: 
- name: simple-dashboard-from-cm
  files:
  - simple-dashboard.json

# generatorOptions:
#   disableNameSuffixHash: true
